### ISSUE TITLE
Section 4.1: Handling of unknown HMAC Identifier

### ISSUE THREAD

**Issue by tuexen** [sctplab/rfc4895bis#14]
Not that this could not happen that an unknown algorithm is used. But it really should not happen. After the Init and Init-ACK each peer will provide what they support. And it does represent a security issue. Because can you after having negotiated use of SCTP-AUTH even trust a packet with a non supported algorithm identifier?

This was reported in [Comments on draft-tuexen-tsvwg-rfc4895-bis-04](https://mailarchive.ietf.org/arch/browse/tsvwg/?q=Comments%20on%20draft-tuexen-tsvwg-rfc4895-bis-04).

**Comment by tuexen** [comment]
I think the document should specify how to handle a received AUTH chunk with a unsupported HMAC identifier. This can be one not supported at all or one that was not requested during the handshake.

Potential ways of handling are:
1. ABORT the association
2. Silently drop the chunks after the AUTH chunk
3. Drop the AUTH chunks after the AUTH chunk and send an ERROR

The first way would allow an attacker to drop the association, which is not acceptable. The third way does allow an attacker to trigger the sending of ERROR chunk, but this does not result in an association failure. The second solution would hide any problems.
If an end point receives such an ERROR chunk, it knows that one side is violating the spec or there is an attack going on.

@gloinul Could you elaborate why you consider this a security issue?

We can change the text to use the second way instead of the third. That would make the handling of an unsupported HMAC Identifier consistent with an unconfigured Key Identifier. But I want to make sure I understand your point completely.

**Comment by tuexen** [comment]
The more I think about this, the more I like to use the second solution. Deprecate the sending of the error cause and require a receiver to silently ignore it. This gets backwards compatibility.
@gloinul OK?

**Comment by gloinul** [comment]
So I think this is safe, with the strict requirement to have all chunk types listed in the chunks parameter to be included in the auth, and if one discard all those given that they either are outside of the AUTH chunk, or the AUTH chunk is not possible to validate this should be safe. 

So, it looks like silently drop ("likely should add a "MAY/SHOULD log these events" is likely a good solution. Not sending an error avoids having an intentional modification result in a response packet. On the down side a persistent error in this will result in that association will time out as the SACK will report no received packets. If the feedback path is not attacked the sender will not know what caused the issue, but the receiver of the damaged packets will know the symptoms it received. So I think that is acceptable but not ideal. But, I think not reporting the error for every packet is better than doing it.
